#! /usr/bin/env python

"""
Usage: run-test [OPTIONS]

Run a testcase.
"""

import os

from testsuite_support import Testsuite

if __name__ == '__main__':
    Testsuite(os.path.dirname(__file__)).test_main()
